version: "3.3"
services:
  nginx:
    image: nginx:1.15.5-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cofferver
  mysql:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testdev

  cofferver:
    image: node:10.12.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: "/app"
    command: "yarn nodemon index.js"
    depends_on: 
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=test
      - DB_PASS=testdev
      - ORIGIN=http://localhost:8080
