version: "3.3"
services:
  mysql:
    image: mysql:5.7.23
    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testdev

  cofferver:
    image: node:10.12.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: "/app"
    command: "yarn dev"
    depends_on: 
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=test
      - DB_PASS=testdev
