version: "3.3"
services:
  nginx:
    image: nginx:1.15.5-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ngnix.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/logs/access.log:/etc/nginx/access.log
      - /etc/nginx/logs/error.log:/etc/nginx/error.log
      - /docker-volumes/etc/letsencrypt/live/api.coffeewheel.xyz/fullchain.pem:/etc/letsencrypt/live/api.coffeewheel.xyz/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/api.coffeewheel.xyz/privkey.pem:/etc/letsencrypt/live/api.coffeewheel.xyz/privkey.pem      
    depends_on:
      - cofferver
  mysql:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=uFa91AomUbnDgH7GsclFBXU

  cofferver:
    image: node:10.12.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: "/app"
    command: "yarn nodemon index.js"
    depends_on: 
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=coffee
      - DB_PASS=01AekDHow5SXqFGa8KF6Jg5
      - ORIGIN=https://coffeewheel.xyz
